# P = Player
# E = Enemy
# # = Wall

[[level]]
name = "Level 1"
type = "vertical"
# maybe put tile size
layout = """
############
#          #
#          #
S   E      #
#####      #
#          #
#          #
#        E #
#  #########
#          #
#          #
# P        #
############
"""

[[level]]
name = "Level 2"
type = "vertical"
layout = """
#################
#               #
# E             #
##########      #
#               #
#        E      #
#  ###########  #
#               #
# P             #
#################
"""
