# P = Player
# E = Enemy
# S = Exit
# # = Wall

# size: 2#v x 19h

[[level]]
name = "Level 1"
type = "vertical"
# maybe put tile size
layout = """
########################
#                   #  S
#                   #  #
#    ##########     #  #
#   ##         ##   #  #
#  ##   ###     ##  # ##
#  #   ## ###    #  #  #
#  #   #         #  #  #
#  #   ##    #####  #  #
## #    ##          #  #
#  #     ###       ### #
#  ###     #####   ##  #
#   ######      #####  #
# ###    ###       #   #
#   #       ####   #   #
#   #  ##         ##  ##
#   #   ###########    #
#P  #                  #
########################
"""

[[level]]
name = "Level 2"
type = "vertical"
layout = """
#################
#               #
# E             S
##########   ####
#               #
#        E      #
#  ###########  #
#               #
# P             #
#################
"""
