# P = Player
# E = Enemy
# S = Exit
# # = Wall

# size: 2#v x 19h

[[level]]
name = "Level 1"
type = "vertical"
# maybe put tile size
layout = """
########################
#                 E #  S
#                   #  #
#    ##########     #  #
#   ##         ##   #  #
#  ##   ###     ##  # ##
#  #   ## ###    #  #  #
#  #   #         #  #  #
#  #   ##    #####  #  #
## #    ##          #  #
#  #     ###       ### #
#  ###     #####   ##  #
#   ######      #####  #
# ###    ###       #   #
#   #       ####   #   #
#   #  ##         ##  ##
#   #   ###########    #
#P                     #
########################
"""

[[level]]
name = "Level 2"
type = "vertical"
layout = """
#################
#               #
# E             S
##########   ####
#               #
######## # #    #
#          #    #
#          #    #
#  ###########  #
#       #       #
# P     #       #
#################
"""

[[level]]
name = "Level 3"
type = "vertical"
layout = """
#######################
#      ###            #
#     ##       ###    #
#   E##    E     #S#  #
#   ##   ####    ###  #
#  ##   #    ##       #
# ##    #    ##  ###  #
# #    ##     ##    # #
# #   ### ###  ###  # #
# #        # E        #
# #    #########    ###
# ###      #   ##   ###
#   ####   #    ##   ##
#     ######       ####
#P              #######
#######################
"""

[[level]]
name = "Level 4"
type = "vertical"
layout = """
#####################
#       ##          #
#  E    ##    ##    #
####        ##  ##  #
#       ###    ##   #
#   ##       ###    #
#   ######          #
#   ##   ## ###     #
# S ##    #    ##   #
####   #######      #
####   #          ###
####   ##   #########
#  ###              #
#    #######   ##   #
#  P           ##   #
#####################
"""