# P = Player
# E = Enemy
# # = Wall

[[level]]
name = "Level 1"
type = "vertical"
layout = """
########
#      #
# E    #
#####  #
#      #
#      #
#  #####
#      #
# P    #
########
"""

[[level]]
name = "Level 2"
type = "vertical"
layout = """
#################
#               #
#               #
######## # #    #
#          #    #
#          #    #
#  ###########  #
#       #       #
# P     #       #
#################
"""
